language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
- yarn danger ci
script:
  - yarn add jest
  - yarn run test --outputFile test-results.json --json
  - yarn run build
  - yarn run danger
  - rm -f test-results.json
